[falcon]
name = "Moto G"
family = "MotoKitKat"
width = 720
height = 1280

[harpia]
name = "Moto G4 Play"
family = "MotoKitKat"
width = 720
height = 1280

[athene]
name = "Moto G4 / Moto G4 Plus"
family = "MotoKitKat"
width = 1080
height = 1920

[lux]
name = "Moto X Play"
family = "MotoKitKat"
width = 1080
height = 1920

[oneplus2]
name = "OnePlus 2"
family = "OnePlus2"
width = 1080
height = 1920

[oneplus3]
name = "OnePlus 3"
family = "OnePlus2"
width = 1080
height = 1920
